# Generated by Django 4.2.2 on 2023-08-03 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitShareApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_program',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
