# Generated by Django 4.2.2 on 2023-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitShareApp', '0003_alter_user_gender_alter_user_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
